# Project information
site_name: Vapor Docs
site_url: https://docs.vapor.codes/
site_author: Vapor Community
site_description: Vapors documentation (web framework for Swift).

# Repository
repo_name: Vapor GitHub
repo_url: http://github.com/vapor/vapor
edit_uri: https://github.com/vapor/documentation/edit/main/docs/

# Copyright
copyright: "Copyright &copy; Vapor Community"

# Configuration
theme:
  name: material
  custom_dir: theme/
  language: en
  locale: en
  font: false

  palette:
    primary: black
    accent: blue

  logo: assets/logo.png
  favicon: assets/favicon.png

  features:
    - search.suggest
    - search.highlight

# Customization
extra:
  # Font
  font:
    text: Roboto Slab
    code: Source Code Pro

  # Social
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/codevapor
    - icon: fontawesome/brands/discord
      link: https://discord.gg/vapor
    - icon: fontawesome/brands/github
      link: https://github.com/vapor

extra_css:
  - stylesheets/syntax.css
  - stylesheets/fonts.css

extra_javascript:
  - javascripts/syntax.js

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true

# Plugins
plugins:
  - search:
      lang: en
  # i18n plugin documentation
  # https://github.com/ultrabug/mkdocs-static-i18n
  - i18n:
      default_language: 'en'
      search_reconfigure: false
      material_alternate: true
      # Add the new languages here. DON'T CHANGE THE DEFAULT LANGUAGE
      languages:
        en:
          name: English
          build: true
        zh:
          name: 简体中文
          site_name: Vapor 中文文档
          build: true
        nl:
          name: Nederlands
          site_name: Vapor Documentatie
          build: true
        fr:
          name: Français
          site_name: Documentation Vapor
          build: true
        de:
          name: German
          site_name: Vapor Dokumentation
          build: true
      # Add navigation translations here
      nav_translations:
        nl:
          Welcome: Welkom
          Install: Installeren
          Getting Started: Aan De Slag
          Hello, world: Hallo, wereld
          Folder Structure: Folder Structuur
          Basics: Basis
          Routing: Routering
          Content: Inhoud
          Validation: Validatie
          Async: Asynchroon
          Logging: Loggen
          Environment: Omgeving
          Overview: Overzicht
          Relations: Relaties
          Migrations: Migraties
          Query: Opvragen
          Transactions: Transacties
          Schema: Schema
          Advanced: Geavanceerd
          Testing: Testen
          Files: Bestanden
          Commands: Commando's
          Queues: Wachtrijen
          Sessions: Sessies
          Services: Diensten
          Security: Veiligheid
          Authentication: Authenticatie
          Crypto: Encryptie
          Passwords: Wachtwoorden
          Deploy: Opzetten
          Version (4.0): Versie (4.0)
          Legacy Docs: Oude Documentatie
          Upgrading: Upgraden
          Custom Tags: Zelfgemaakte Tags
          Contributing: Bijdragen
          Contributing Guide: Gids Bijdragen
        fr: 
          Welcome: Bienvenue
        de:
          Welcome: Willkommen
        zh:
          Welcome: 序言
          Install: 安装
          Getting Started: 开始
          Hello, world: 你好世界
          Folder Structure: 项目结构
          SwiftPM: Swift 包管理器
          Xcode: Xcode
          Basics: 入门
          Routing: 路由
          Content: 内容
          Client: 客户端
          Validation: 验证
          Async: 异步
          Logging: 日志
          Environment: 环境
          Errors: 错误
          Fluent: Fluent
          Overview: 概述
          Model: 模型
          Relations: 关联
          Migrations: 迁移
          Query: 查询
          Transactions: 事务
          Schema: 模式
          Leaf: Leaf
          Custom Tags: 自定义标签
          Redis: Redis
          Advanced: 进阶
          Middleware: 中间件
          Testing: 测试
          Server: 服务器
          Files: 文件
          Commands: 命令
          Queues: 队列
          WebSockets: 即时通讯
          Sessions: 会话
          Services: 服务
          Security: 安全
          APNS: 苹果推送服务
          Deploy: 部署
          Authentication: 认证
          Crypto: 加密
          Passwords: 密码
          JWT: JWT
          Contributing: 贡献
          Contributing Guide: 贡献指南
          Version (4.0): 版本 (4.0)


nav:
- Welcome: "index.md"
- Install:
  - macOS: "install/macos.md"
  - Linux: "install/linux.md"
- Getting Started:
  - Hello, world: "getting-started/hello-world.md"
  - Folder Structure: "getting-started/folder-structure.md"
  - SwiftPM: "getting-started/spm.md"
  - Xcode: "getting-started/xcode.md"
- Basics:
  - Routing: "basics/routing.md"
# TODO: Improve quality
# Mostly just a code sample with little explanation.
#  - Controllers: "controllers.md"
  - Content: "basics/content.md"
  - Client: "basics/client.md"
  - Validation: "basics/validation.md"
  - Async: "basics/async.md"
  - Logging: "basics/logging.md"
  - Environment: "basics/environment.md"
  - Errors: "basics/errors.md"
- Fluent:
  - Overview: "fluent/overview.md"
  - Model: "fluent/model.md"
  - Relations: "fluent/relations.md"
  - Migrations: "fluent/migration.md"
  - Query: "fluent/query.md"
  - Transactions: "fluent/transaction.md"
  - Schema: "fluent/schema.md"
  - Advanced: "fluent/advanced.md"
- Leaf:
  - Getting Started: "leaf/getting-started.md"
  - Overview: "leaf/overview.md"
  - Custom Tags: "leaf/custom-tags.md"
- Redis:
  - Overview: "redis/overview.md"
  - Sessions: "redis/sessions.md"
- Advanced:
  - Middleware: "advanced/middleware.md"
  - Testing: "advanced/testing.md"
  - Server: "advanced/server.md"
  - Files: "advanced/files.md"
  - Commands: "advanced/commands.md"
  - Queues: "advanced/queues.md"
  - WebSockets: "advanced/websockets.md"
  - Sessions: "advanced/sessions.md"
  - Services: "advanced/services.md"
  - APNS: "advanced/apns.md"
- Security:
  - Authentication: "security/authentication.md"
  - Crypto: "security/crypto.md"
  - Passwords: "security/passwords.md"
  - JWT: "security/jwt.md"
- Deploy:
  - DigitalOcean: "deploy/digital-ocean.md"
  - Heroku: "deploy/heroku.md"
  - Supervisor: "deploy/supervisor.md"
  - Systemd: "deploy/systemd.md"
  - Nginx: "deploy/nginx.md"
  - Docker: "deploy/docker.md"
- Contributing:
  - Contributing Guide: "contributing/contributing.md"
- Version (4.0):
    - Legacy Docs: "version/legacy-docs.md"
    - Upgrading: "upgrading.md"
