# Project information
site_name: Vapor Docs
site_url: https://docs.vapor.codes/
site_author: Vapor Community
site_description: Vapors documentation (web framework for Swift).

# Repository
repo_name: Vapor GitHub
repo_url: http://github.com/vapor/vapor
edit_uri: https://github.com/vapor/documentation/edit/main/docs/

# Copyright
copyright: "Vapor Documentation &copy; 2023 by Vapor is licensed under CC BY-NC-SA 4.0"

# Configuration
theme:
  name: material
  custom_dir: theme/
  language: en
  locale: en
  font: false

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      accent: blue
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      accent: blue
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  logo: assets/logo.png
  favicon: assets/favicon.png

  features:
    - search.suggest
    - search.highlight

# Customization
extra:
  # Font
  font:
    text: Roboto Slab
    code: Source Code Pro

  # Social
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/codevapor
    - icon: fontawesome/brands/discord
      link: https://discord.gg/vapor
    - icon: fontawesome/brands/github
      link: https://github.com/vapor
    - icon: fontawesome/brands/mastodon
      link: https://hachyderm.io/@codevapor

extra_css:
  - stylesheets/syntax.css
  - stylesheets/fonts.css

extra_javascript:
  - javascripts/highlight.min.js
  - javascripts/startSyntaxHighlighting.js

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - meta
  - attr_list
  - toc:
      permalink: true

# Plugins
plugins:
  - search:
      lang: en
  # i18n plugin documentation
  # https://github.com/ultrabug/mkdocs-static-i18n
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      languages:
        - build: true
          default: true
          locale: en
          name: English
        - build: true
          default: false
          locale: zh
          name: 简体中文
          nav_translations:
            APNS: 苹果推送服务
            Advanced: 进阶
            Async: 异步
            Authentication: 认证
            Basics: 入门
            Client: 客户端
            Commands: 命令
            Content: 内容
            Contributing: 贡献
            Contributing Guide: 贡献指南
            Crypto: 加密
            Custom Tags: 自定义标签
            Deploy: 部署
            Environment: 环境
            Errors: 错误
            Files: 文件
            Fluent: Fluent
            Folder Structure: 项目结构
            Getting Started: 开始
            Hello, world: 你好世界
            Install: 安装
            JWT: JWT
            Leaf: Leaf
            Logging: 日志
            Middleware: 中间件
            Migrations: 迁移
            Model: 模型
            Overview: 概述
            Passwords: 密码
            Query: 查询
            Queues: 队列
            Redis: Redis
            Relations: 关联
            Routing: 路由
            Schema: 模式
            Security: 安全
            Server: 服务器
            Services: 服务
            Sessions: 会话
            SwiftPM: Swift 包管理器
            Testing: 测试
            Transactions: 事务
            Validation: 验证
            Version (4.0): 版本 (4.0)
            WebSockets: 即时通讯
            Welcome: 序言
            Xcode: Xcode
          site_name: Vapor 中文文档
        - build: true
          default: false
          locale: nl
          name: Nederlands
          nav_translations:
            Advanced: Geavanceerd
            Async: Asynchroon
            Authentication: Authenticatie
            Basics: Basis
            Commands: Commando's
            Content: Inhoud
            Contributing: Bijdragen
            Contributing Guide: Gids Bijdragen
            Crypto: Encryptie
            Custom Tags: Zelfgemaakte Tags
            Deploy: Opzetten
            Environment: Omgeving
            Files: Bestanden
            Folder Structure: Folder Structuur
            Getting Started: Aan De Slag
            Hello, world: Hallo, wereld
            Install: Installeren
            Legacy Docs: Oude Documentatie
            Logging: Loggen
            Migrations: Migraties
            Overview: Overzicht
            Passwords: Wachtwoorden
            Query: Opvragen
            Queues: Wachtrijen
            Relations: Relaties
            Routing: Routering
            Schema: Schema
            Security: Veiligheid
            Services: Diensten
            Sessions: Sessies
            Testing: Testen
            Transactions: Transacties
            Upgrading: Upgraden
            Validation: Validatie
            Version (4.0): Versie (4.0)
            Welcome: Welkom
          site_name: Vapor Documentatie
        - build: true
          default: false
          locale: fr
          name: Français
          nav_translations:
            Advanced: Avancé
            Async: Asynchrone
            Authentication: Authentification
            Basics: Bases
            Commands: Commandes
            Content: Contenu
            Contributing: Contribuer
            Contributing Guide: Guide de contribution
            Controllers: Contrôleurs
            Custom Tags: Tags customisés
            Errors: Erreurs
            Deploy: Deployer
            Environment: Environement
            Files: Fichiers
            Folder Structure: Structure du Dossier
            Getting Started: Commencer
            Hello, world: Bonjour, monde
            Install: Installer
            Legacy Docs: Documents hérité
            Migrations: Migrations
            Overview: Aperçu
            Passwords: Mots de passe
            Query: Requête
            Queues: Files d'attente
            Relataions: Relations
            Release Notes: Notes de Version
            Request: Requête
            Routing: Routage
            Schema: Schema
            Security: Securité
            Services: Services
            Sessions: Sessions
            Testing: Test
            Transactions: Transactions
            Upgrading: Mettre à jour
            Validation: Validation
            Version (4.0): Version (4.0)
            Welcome: Bienvenue
          site_name: Documentation Vapor
        - build: true
          default: false
          locale: de
          name: German
          nav_translations:
            Advanced: Erweitert
            Authentication: Authentifzierung
            Basics: Grundlagen
            Commands: Befehle
            Content: Modelbindung
            Contributing: Mitwirken
            Contributing Guide: Leitfaden für Beiträge
            Deploy: Bereitstellung
            Environment: Umgebung
            Errors: Fehlerbehandlung
            Files: Dateien
            Folder Structure: Verzeichnis
            Getting Started: Einführung
            Hello, world: Hallo Welt
            Install: Installation
            Logging: Protokollierung
            Migrations: Migrationen
            Model: Models
            Overview: Übersicht
            Query: Abfrage
            Relations: Beziehungen
            Security: Sicherheit
            Services: Dienste
            Sessions: Sitzungen
            Testing: Testen
            Transactions: Transaktionen
            Validation: Validierung
            Welcome: Begrüßung
          site_name: Vapor Dokumentation
        - build: true
          default: false
          locale: it
          name: Italiano
          nav_translations:
            APNS: APNS
            Advanced: Avanzate
            Async: Asincrono
            Authentication: Autenticazione
            Basics: Basi
            Client: Client
            Commands: Comandi
            Content: Contenuto
            Contributing: Contribuire
            Contributing Guide: Guida alla Contribuzione
            Controllers: Controller
            Crypto: Crittografia
            Custom Tags: Tag Personalizzati
            Deploy: Deploy
            Environment: Ambiente
            Errors: Errori
            Files: File
            Fluent: Fluent
            Folder Structure: Struttura della Cartella
            Getting Started: Inizio
            Hello, world: Ciao, mondo
            Install: Installazione
            JWT: JWT
            Leaf: Leaf
            Legacy Docs: Documentazione Obsoleta
            Logging: Logging
            Middleware: Middleware
            Migrations: Migrazioni
            Model: Modello
            Overview: Panoramica
            Passwords: Password
            Query: Query
            Queues: Code
            Redis: Redis
            Relations: Relazioni
            Release Notes: Note sulla Versione
            Routing: Routing
            Schema: Schema
            Security: Sicurezza
            Server: Server
            Services: Servizi
            Sessions: Sessioni
            SwiftPM: SwiftPM
            Testing: Test
            Transactions: Transazioni
            Upgrading: Aggiornamento
            Validation: Validazione
            Version (4.0): Versione (4.0)
            WebSockets: WebSockets
            Welcome: Benvenuto
            Xcode: Xcode
          site_name: Documentazione di Vapor
        - build: true
          default: false
          locale: es
          name: Español
          nav_translations:
            APNS: APNS
            Advanced: Avanzado
            Async: Asincronía
            Authentication: Autenticación
            Basics: Fundamentos
            Client: Cliente
            Commands: Comandos
            Content: Content
            Contributing: Colaborar
            Contributing Guide: Guía para Colaborar
            Controllers: Controladores
            Crypto: Criptografía
            Custom Tags: Etiquetas Personalizadas
            Deploy: Desplegar
            Environment: Entorno
            Errors: Errores
            Files: Ficheros
            Fluent: Fluent
            Folder Structure: Estructura de Carpetas
            Getting Started: Comenzando
            Hello, world: Hola, mundo
            Install: Instalación
            JWT: JWT
            Leaf: Leaf
            Legacy Docs: Documentación Legacy
            Logging: Logging
            Middleware: Middleware
            Migrations: Migraciones
            Model: Modelo
            Overview: Presentación
            Passwords: Contraseñas
            Query: Consultas
            Queues: Colas
            Redis: Redis
            Relations: Relaciones
            Routing: Routing
            Schema: Esquema
            Security: Seguridad
            Server: Servidor
            Services: Servicios
            Sessions: Sesiones
            SwiftPM: SwiftPM
            Testing: Testing
            Transactions: Transacciones
            Upgrading: Actualizar
            Validation: Validación
            Version (4.0): Versión (4.0)
            WebSockets: WebSockets
            Welcome: Bienvenido
            Xcode: Xcode
          site_name: Documentación de Vapor
        - build: true
          default: false
          locale: pl
          name: Polski
          nav_translations:
            APNS: APNS
            Advanced: Zaawansowane
            Async: Asynchroniczność
            Authentication: Autentykacja
            Basics: Podstawy
            Client: Klient
            Commands: Komendy
            Content: Kontent
            Contributing: Kontrybucja
            Contributing Guide: Przewodnik do kontrybucji
            Crypto: Kryptografia
            Custom Tags: Własne tagi
            Deploy: Wdrożenie
            Environment: Środowisko
            Errors: Błędy
            Files: Pliki
            Fluent: Fluent
            Folder Structure: Struktura folderów
            Getting Started: Jak zacząć
            Hello, world: Witaj, świecie
            Install: Instalacja
            JWT: JWT
            Leaf: Leaf
            Legacy Docs: Przestażała dokumentacja
            Logging: Logowanie
            Middleware: Middleware
            Migrations: Migracje
            Model: Model
            Overview: Prezentacja
            Passwords: Hasła
            Query: Zapytania
            Queues: Kolejki
            Redis: Redis
            Relations: Relacje
            Release Notes: Informacja o wersji
            Routing: Kierowanie ruchem
            Schema: Schematy
            Security: Bezpieczeństwo
            Server: Serwer
            Services: Serwisy
            Sessions: Sesje
            SwiftPM: SwiftPM
            Testing: Testowanie
            Transactions: Transakcje
            Upgrading: Aktualizacja
            Validation: Walidacja
            Version (4.0): Wersja (4.0)
            WebSockets: WebSockety
            Welcome: Witaj
            Xcode: Xcode
          site_name: Dokumentacja Vapor
        - build: true
          default: false
          locale: ko
          name: 한국어
          nav_translations:
            Advanced: 고급
            Async: 비동기 처리
            Authentication: 인증
            Basics: 기본 사항
            Client: 클라이언트
            Commands: 명령어
            Content: 컨텐츠
            Contributing: 기여하기
            Contributing Guide: 기여 가이드
            Crypto: 암호화
            Custom Tags: 사용자 정의 태그
            Deploy: 배포
            Environment: 환경 설정
            Errors: 에러
            Files: 파일
            Folder Structure: 폴더 구조
            Getting Started: 시작하기
            Install: 설치
            Legacy Docs: 이전 문서
            Logging: 로깅
            Migrations: 마이그레이션
            Model: 모델
            Overview: 개요
            Passwords: 비밀번호
            Query: 쿼리
            Queues: 대기열
            Relations: 관계
            Routing: 라우팅
            Schema: 스키마
            Security: 보안
            Services: 서비스
            Sessions: 세션
            Testing: 테스트
            Transactions: 트랜잭션
            Upgrading: 업그레이드
            Validation: 유효성 검사
            Version (4.0): 버전 (4.0)
            WebSockets: 웹소켓
            Welcome: 환영합니다
          site_name: Vapor 문서
        - build: true
          default: false
          locale: ja
          name: 日本語
          nav_translations:
            Advanced: 上級
            Async: 非同期
            Authentication: 認証
            Basics: 基礎
            Client: クライアント
            Commands: コマンド
            Content: コンテンツ
            Contributing: 貢献
            Contributing Guide: 貢献ガイド
            Controllers: コントローラー
            Crypto: 暗号
            Custom Tags: カスタムタグ
            Deploy: デプロイ
            Environment: 環境
            Errors: エラー
            Files: ファイル
            Folder Structure: フォルダ構造
            Getting Started: はじめに
            Install: インストール
            Legacy Docs: レガシードキュメント
            Logging: ロギング
            Migrations: マイグレーション
            Model: モデル
            Overview: 概要
            Passwords: パスワード
            Query: クエリ
            Queues: キュー
            Relations: 関係
            Release Notes: リリースノート
            Routing: ルーティング
            Schema: スキーマ
            Security: セキュリティ
            Services: サービス
            Sessions: セッション
            Testing: テスト
            Transactions: トランザクション
            Upgrading: アップグレード
            Validation: バリデーション
            Welcome: ようこそ
          site_name: Vapor ドキュメント
      reconfigure_material: true
      reconfigure_search: false
nav:
- Welcome: "index.md"
- Install:
  - macOS: "install/macos.md"
  - Linux: "install/linux.md"
- Getting Started:
  - Hello, world: "getting-started/hello-world.md"
  - Folder Structure: "getting-started/folder-structure.md"
  - SwiftPM: "getting-started/spm.md"
  - Xcode: "getting-started/xcode.md"
- Basics:
  - Routing: "basics/routing.md"
# TODO: Improve quality
# Mostly just a code sample with little explanation.
  - Controllers: "basics/controllers.md"
  - Content: "basics/content.md"
  - Client: "basics/client.md"
  - Validation: "basics/validation.md"
  - Async: "basics/async.md"
  - Logging: "basics/logging.md"
  - Environment: "basics/environment.md"
  - Errors: "basics/errors.md"
- Fluent:
  - Overview: "fluent/overview.md"
  - Model: "fluent/model.md"
  - Relations: "fluent/relations.md"
  - Migrations: "fluent/migration.md"
  - Query: "fluent/query.md"
  - Transactions: "fluent/transaction.md"
  - Schema: "fluent/schema.md"
  - Advanced: "fluent/advanced.md"
- Leaf:
  - Getting Started: "leaf/getting-started.md"
  - Overview: "leaf/overview.md"
  - Custom Tags: "leaf/custom-tags.md"
- Redis:
  - Overview: "redis/overview.md"
  - Sessions: "redis/sessions.md"
- Advanced:
  - Middleware: "advanced/middleware.md"
  - Testing: "advanced/testing.md"
  - Server: "advanced/server.md"
  - Files: "advanced/files.md"
  - Commands: "advanced/commands.md"
  - Queues: "advanced/queues.md"
  - WebSockets: "advanced/websockets.md"
  - Sessions: "advanced/sessions.md"
  - Services: "advanced/services.md"
  - Request: "advanced/request.md"
  - APNS: "advanced/apns.md"
- Security:
  - Authentication: "security/authentication.md"
  - Crypto: "security/crypto.md"
  - Passwords: "security/passwords.md"
  - JWT: "security/jwt.md"
- Deploy:
  - DigitalOcean: "deploy/digital-ocean.md"
  - Fly: "deploy/fly.md"
  - Heroku: "deploy/heroku.md"
  - Supervisor: "deploy/supervisor.md"
  - Systemd: "deploy/systemd.md"
  - Nginx: "deploy/nginx.md"
  - Docker: "deploy/docker.md"
- Contributing:
  - Contributing Guide: "contributing/contributing.md"
- Version (4.0):
    - Legacy Docs: "version/legacy-docs.md"
    - Upgrading: "upgrading.md"
- Release Notes: "release-notes.md"
