site_name: 'Vapor Docs'
copyright: 'Copyright &copy; 2017 Qutheory, LLC'

pages:
- Overview: 'index.md'
- Getting started:
    - 'Install: macOS': 'getting-started/install-on-macos.md'
    - 'Install: Ubuntu': 'getting-started/install-on-ubuntu.md'
    - 'Toolbox': 'getting-started/toolbox.md'
    - 'Hello, World': 'getting-started/hello-world.md'
    - 'Manual': 'getting-started/manual.md'
    - 'Xcode': 'getting-started/xcode.md'
- Vapor:
    - 'Folder Structure': 'vapor/folder-structure.md'
    - 'Droplet': 'vapor/droplet.md'
    - 'Views': 'vapor/views.md'
    - 'Controllers': 'vapor/controllers.md'
    - 'Provider': 'vapor/provider.md'
    - 'Hash': 'vapor/hash.md'
    - 'Log': 'vapor/log.md'
    - 'Commands': 'vapor/commands.md'
- Configs:
    - 'Config': 'configs/config.md'
- JSON: 
    - 'Package': 'json/package.md'
    - 'Overview': 'json/overview.md'
- Routing:
    - 'Package': 'routing/package.md'
    - 'Overview': 'routing/overview.md'
    - 'Parameters': 'routing/parameters.md'
    - 'Group': 'routing/group.md'
    - 'Collection': 'routing/collection.md'
- Fluent:
    - 'Package': 'fluent/package.md'
    - 'Getting Started': 'fluent/getting-started.md'
    - 'Model': 'fluent/model.md'
    - 'Database': 'fluent/database.md'
    - 'Query': 'fluent/query.md'
    - 'Relations': 'fluent/relations.md'
- Cache: 
    - 'Package': 'cache/package.md'
    - 'Overview': 'cache/overview.md'
- MySQL:
    - 'Package': 'mysql/package.md'
    - 'Provider': 'mysql/provider.md'
    - 'Driver': 'mysql/driver.md'
- Redis:
    - 'Package': 'redis/package.md'
    - 'Provider': 'redis/provider.md'
- Auth:
    - 'Package': 'auth/package.md'
    - 'Provider': 'auth/provider.md'
    - 'Getting Started': 'auth/getting-started.md'
    - 'Helper': 'auth/helper.md'
    - 'Password': 'auth/password.md'
    - 'Persist': 'auth/persist.md'
    - 'Redirect Middleware': 'auth/redirect-middleware.md'
- JWT:
    - 'Package': 'jwt/package.md'
    - 'Overview': 'jwt/overview.md'
- Sessions:
    - 'Package': 'sessions/package.md'
    - 'Sessions': 'sessions/sessions.md'
- HTTP:
    - 'Package': 'http/package.md'
    - 'Request': 'http/request.md'
    - 'Response': 'http/response.md'
    - 'Middleware': 'http/middleware.md'
    - 'Body': 'http/body.md'
    - 'ResponseRepresentable': 'http/response-representable.md'
    - 'Responder': 'http/responder.md'
    - 'Client': 'http/client.md'
    - 'Server': 'http/server.md'
    - 'CORS': 'http/cors.md'
- Leaf:
    - 'Package': 'leaf/package.md'
    - 'Provider': 'leaf/provider.md'
    - 'Overview': 'leaf/leaf.md'
- Validation (WIP):
    - 'Package': 'validation/package.md'
    - 'Overview': 'validation/overview.md'
- Node:
    - 'Package': 'node/package.md'
    - 'Getting Started': 'node/getting-started.md'
- Core: 
    - 'Package': 'core/package.md'
    - 'Overview': 'core/overview.md'
- Bits: 
    - 'Package': 'bits/package.md'
    - 'Overview': 'bits/overview.md'
- Debugging: 
    - 'Package': 'debugging/package.md'
    - 'Overview': 'debugging/overview.md'
- Deploy:
    - 'Cloud': 'deploy/cloud.md'
    - 'Nginx': 'deploy/nginx.md'
    - 'Apache2': 'deploy/apache2.md'
    - 'Supervisor': 'deploy/supervisor.md'
- Version (2.0):
    - '1.5': 'version/1_5.md'
    - '2.0': 'version/2_0.md'
    - '3.0': 'version/3_0.md'
    - 'Support': 'version/support.md'

markdown_extensions:
    - admonition
    - codehilite(guess_lang=false)
    - footnotes
    - meta
    - toc(permalink=true)

theme: 
    name: 'material'
    palette:
        primary: 'grey'
        accent: 'grey'
    logo: 'images/droplet-white.svg'

repo_url: http://github.com/vapor/vapor
edit_uri: https://github.com/vapor/documentation/edit/master/2.0/docs/

extra:
    logo: 'images/droplet-white.svg'
    social:
        - type: 'twitter'
          link: 'https://twitter.com/@codevapor'
        - type: 'slack'
          link: 'http://vapor.team/'
    font:
        text: 'Roboto Slab'
        code: 'Source Code Pro'
    
google_analytics:
    - 'UA-76177358-4'
    - 'auto'
