site_name: 'Vapor Docs'
copyright: 'Copyright &copy; 2018 Qutheory, LLC'

pages:
- 'Overview': 'index.md'
- 'Install':
    - 'macOS': 'install/macos.md'
    - 'Ubuntu': 'install/ubuntu.md'
- 'Getting Started':
    - 'Hello, world': 'getting-started/hello-world.md'
    - 'Toolbox': 'getting-started/toolbox.md'
    - 'SPM': 'getting-started/spm.md'
    - 'Xcode': 'getting-started/xcode.md'
    - 'Folder Structure': 'getting-started/structure.md'
    - 'Application': 'getting-started/application.md'
    - 'Controllers': 'getting-started/controllers.md'
    - 'Routing': 'getting-started/routing.md'
    - 'Content': 'getting-started/content.md'
    - 'Async': 'getting-started/async.md'
    - 'Services': 'getting-started/services.md'
    - 'Deployment': 'getting-started/cloud.md'
- 'Async':
    - 'Getting Started': 'async/getting-started.md'
    - 'Overview': 'async/overview.md'
- 'Console':
    - 'Getting Started': 'console/getting-started.md'
    - 'Overview': 'console/overview.md'
- 'Command':
    - 'Getting Started': 'command/getting-started.md'
    - 'Overview': 'command/overview.md'
- 'Core':
    - 'Getting Started': 'core/getting-started.md'
    - 'Overview': 'core/overview.md'
- 'Crypto':
    - 'Getting Started': 'crypto/getting-started.md'
    - 'Digests': 'crypto/digests.md'
    - 'Ciphers': 'crypto/ciphers.md'
    - 'Asymmetric': 'crypto/asymmetric.md'
    - 'Random': 'crypto/random.md'
- 'Fluent':
    - 'Getting Started': 'fluent/getting-started.md'
    - 'Models': 'fluent/models.md'
    - 'Migrations': 'fluent/migrations.md'
    - 'Querying': 'fluent/querying.md'
    - 'Query Builder': 'fluent/query-builder.md'
    - 'Schema Builder': 'fluent/schema-builder.md'
    - 'Relations': 'fluent/relations.md'
    - 'Pivot': 'fluent/pivot.md'
    - 'Transaction': 'fluent/transaction.md'
    - 'Database': 'fluent/database.md'
- 'Leaf':
    - 'Getting Started': 'leaf/getting-started.md'
    - 'Basics': 'leaf/basics.md'
    - 'Custom tags': 'leaf/custom-tags.md'
- 'Logging':
    - 'Getting Started': 'logging/getting-started.md'
    - 'Overview': 'logging/overview.md'
- 'Multipart':
    - 'Getting Started': 'multipart/getting-started.md'
    - 'Overview': 'multipart/overview.md'
- 'MySQL':
    - 'Getting Started': 'mysql/getting-started.md'
    - 'Fluent MySQL': 'mysql/fluent.md'
    - 'MySQL Core': 'mysql/core.md'
- 'PostgreSQL':
    - 'Getting Started': 'postgresql/getting-started.md'
    - 'Fluent PostgreSQL': 'postgresql/fluent.md'
    - 'PostgreSQL Core': 'postgresql/core.md'
- 'Redis':
    - 'Getting Started': 'redis/getting-started.md'
    - 'Basics': 'redis/basics.md'
    - 'Custom commands': 'redis/custom-commands.md'
    - 'Publish and Subscribe': 'redis/pub-sub.md'
    - 'Pipeline': 'redis/pipeline.md'
- 'Routing':
    - 'Getting Started': 'routing/getting-started.md'
    - 'Parameters': 'routing/parameters.md'
    - 'Route': 'routing/route.md'
    - 'Router': 'routing/router.md'
- 'Service':
    - 'Getting Started': 'service/getting-started.md'
    - 'Services': 'service/services.md'
    - 'Provider': 'service/provider.md'
- 'SQLite':
    - 'Getting Started': 'sqlite/getting-started.md'
    - 'Fluent SQLite': 'sqlite/fluent.md'
    - 'SQLite Core': 'sqlite/core.md'
- 'Template Kit':
    - 'Getting Started': 'template-kit/getting-started.md'
- 'Testing':
    - 'Getting Started': 'testing/getting-started.md'
- 'URL-Encoded Form':
    - 'Getting Started': 'url-encoded-form/getting-started.md'
    - 'Overview': 'url-encoded-form/overview.md'
- 'Validation':
    - 'Getting Started': 'validation/getting-started.md'
    - 'Overview': 'validation/overview.md'
- 'Vapor':
    - 'Getting Started': 'vapor/getting-started.md'
    - 'Content': 'vapor/content.md'
- 'WebSocket': 
    - 'Getting Started': 'websocket/websocket.md'
- 'Version (3.0-rc)':
    - '1.5': 'version/1_5.md'
    - '2.0': 'version/2_0.md'
    - '3.0-rc': 'version/3_0.md'
    - 'Support': 'version/support.md'


markdown_extensions:
    - admonition
    - codehilite(guess_lang=false)
    - footnotes
    - meta
    - toc(permalink=true)

theme:
    name: 'material'
    palette:
        primary: 'blue'
        accent: 'purple'
    logo: 'images/droplet-white.svg'

repo_url: http://github.com/vapor/vapor
edit_uri: https://github.com/vapor/documentation/edit/master/3.0/docs/
extra:
    social:
        - type: 'twitter'
          link: 'https://twitter.com/@codevapor'
        - type: 'slack'
          link: 'http://vapor.team/'
        - type: 'github'
          link: 'https://github.com/vapor'
    font:
        text: 'Roboto Slab'
        code: 'Source Code Pro'

google_analytics:
    - 'UA-76177358-4'
    - 'auto'
