site_name: 'Vapor Docs'
copyright: 'Copyright &copy; 2017 Qutheory, LLC'

pages:
- 'Overview': 'index.md'
- 'Install':
    - 'macOS': 'install/macos.md'
    - 'Ubuntu': 'install/ubuntu.md'
- 'Getting started':
    - 'Hello, world': 'getting-started/hello-world.md'
    - 'Toolbox': 'getting-started/toolbox.md'
    - 'SPM': 'getting-started/spm.md'
    - 'Xcode': 'getting-started/xcode.md'
    - 'Folder Structure': 'getting-started/structure.md'
    - 'Application': 'getting-started/application.md'
    - 'Controllers': 'getting-started/controllers.md'
    - 'Routing': 'getting-started/routing.md'
    - 'Content': 'getting-started/content.md'
    - 'Futures': 'async/futures.md'
    - 'Deployment': 'getting-started/cloud.md'
- 'Concepts':
    - 'Services': 'concepts/services.md'
    - 'HTTP': 'concepts/http.md'
    - 'Code Contributions': 'concepts/code-contributions.md'
- 'Async':
    - 'Getting Started': 'async/getting-started.md'
    - 'Futures': 'async/futures.md'
    - 'Streams': 'async/streams.md'
    - 'EventLoop': 'async/eventloop.md'
- 'HTTP':
    - 'Getting Started': 'http/getting-started.md'
    - 'Client': 'http/client.md'
    - 'Cookies': 'http/cookies.md'
    - 'Message': 'http/message.md'
    - 'Middleware': 'http/middleware.md'
    - 'Multipart': 'http/multipart.md'
- 'Fluent':
    - 'Getting Started': 'fluent/getting-started.md'
    - 'Models': 'fluent/models.md'
    - 'Migrations': 'fluent/migrations.md'
    - 'Querying': 'fluent/querying.md'
    - 'Query Builder': 'fluent/query-builder.md'
    - 'Schema Builder': 'fluent/schema-builder.md'
    - 'Migration': 'fluent/migration.md'
    - 'Relations': 'fluent/relations.md'
    - 'Pivot': 'fluent/pivot.md'
    - 'Transaction': 'fluent/transaction.md'
    - 'Database': 'fluent/database.md'
- 'Databases':
    - 'MongoDB':
        - 'Getting Started': 'databases/mongodb/getting-started.md'
        - 'BSON': 'databases/mongodb/bson.md'
        - 'Basics': 'databases/mongodb/basics.md'
        - 'Interpreting tutorials': 'databases/mongodb/interpreting.md'
    - 'MySQL':
        - 'Getting Started': 'databases/mysql/getting-started.md'
        - 'Basics': 'databases/mysql/basics.md'
        - 'Prepared Statements': 'databases/mysql/prepared-statements.md'
    # - 'PostgreSQL':
    #     - 'Package': 'databases/postgres/getting-started.md'
    #     - 'Setup': 'databases/postgres/setup.md'
    #     - 'Basics': 'databases/postgres/basics.md'
- 'Leaf':
    - 'Getting Started': 'leaf/getting-started.md'
    - 'Basics': 'leaf/basics.md'
    - 'Custom tags': 'leaf/custom-tags.md'
- 'Redis':
    - 'Getting Started': 'redis/getting-started.md'
    - 'Publish & Subscribe': 'redis/pub-sub.md'
- 'WebSocket': 'websocket/websocket.md'
# - 'Routing':
#     - 'Package': 'routing/getting-started.md'
#     - 'Basics': 'routing/basics.md'
#     - 'Parameters': 'routing/parameters.md'
#     - 'Route': 'routing/route.md'
#     - 'Router': 'routing/router.md'
- 'Services': 'concepts/services.md'
- 'JWT':
    - 'Package': 'jwt/getting-started.md'
- 'Crypto':
    - 'Getting Started': 'crypto/getting-started.md'
    - 'Base64': 'crypto/base64.md'
# - 'TLS':
#     - 'Package': 'tls/getting-started.md'
#     - 'Client': 'tls/client.md'
- 'Sockets':
    - 'Getting Started': 'sockets/getting-started.md'
# - 'Testing':
#     - 'Getting Started': 'testing/getting-started.md'
- 'Version (3.0-alpha)':
    - '1.5': 'version/1_5.md'
    - '2.0': 'version/2_0.md'
    - '3.0-alpha': 'version/3_0.md'
    - 'Support': 'version/support.md'


markdown_extensions:
    - admonition
    - codehilite(guess_lang=false)
    - footnotes
    - meta
    - toc(permalink=true)

theme:
    name: 'material'
    palette:
        primary: 'blue'
        accent: 'purple'
    logo: 'images/droplet-white.svg'

repo_url: http://github.com/vapor/vapor
edit_uri: https://github.com/vapor/documentation/edit/beta/3.0/docs/
extra:
    social:
        - type: 'twitter'
          link: 'https://twitter.com/@codevapor'
        - type: 'slack'
          link: 'http://vapor.team/'
        - type: 'github'
          link: 'https://github.com/vapor'
    font:
        text: 'Roboto Slab'
        code: 'Source Code Pro'

google_analytics:
    - 'UA-76177358-4'
    - 'auto'
